name: 'My docker container action'
description: 'Simple action to use cowsay'
inputs:
  what-to-say:
    description: 'What to say'
    default: 'Nothing to say...'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.what-to-say }}
