name: deploy
on: push
  branches:
    - main
  tags:
    - *-dev
jobs:
  main:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: git setting
        run: |
          git config --local user.email unknown@example.com
          git config --local user.name  github_actions
      - name: commit
        run: |
          sed -i -r "s/COMMIT_SHA_.{7}/COMMIT_SHA_${GITHUB_SHA:0:7}/g" ./README.md
          git commit -a -m "replace hash"
          git push origin main
      - name: tag
        run: |
          git tag ${GITHUB_SHA:0:7}
          git push origin --tags
