name: feed
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  main:
    name: bq-release-notes
    runs-on: ubuntu-latest
    steps:
      - name: rss-issues-action
        uses: guilhem/rss-issues-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: "https://cloud.google.com/feeds/bigquery-release-notes.xml"
          prefix: "[BQ]"

