name: feed
on:
  workflow_dispatch
jobs:
  main:
    name: bq-release-notes
    runs-on: ubuntu-latest
    steps:
      - name: rss-issues-action
        uses: guilhem/rss-issues-action@0.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: "https://cloud.google.com/feeds/bigquery-release-notes.xml"
          prefix: "[GKE]"
          dry-run: "false"
          lastTime: "336h"
          labels: "liens/Kubernetes"

