# https://docs.github.com/en/enterprise-cloud@latest/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards
#
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Move assigned card
on:
  issues:
    types:
    - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
    - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
      with:
        project: Docs Work
        column: In Progress
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
