name: exampleWorkflow
on: [push]
jobs:
  exampleJobs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #----- Execute a Command on the Runner -----
    - run: echo 'Hello GitHub Actions'

    #----- Execute a Shell Script on the Runner -----
    # You have to use `actions/checkout@v2` before.
    # Do not forget to add execute permission on the scripts.
    - run: ./.github/scripts/helloworld.sh
