name: exampleWorkflow
on: [push]
jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #----- Execute a Command on the Runner -----
    - run: echo 'Hello GitHub Actions'

    #----- Execute a Shell Script on the Runner -----
    # You have to use `actions/checkout@v2` before.
    # Do not forget to add execute permission on the scripts.
    - run: ./.github/scripts/helloworld.sh

    #----- Docker Container Action -----
    - uses: docker://alpine:latest

    #----- Upload Artifact -----
    - run: |
        echo 'This is an artifact' > artifact.txt
    - run: |
        echo 'added' >> artifact.txt
    - uses: actions.upload-artifact@v3
      with:
        name: example-artifact
        path: artifact.txt

  downloadArtifactJob:
    runs-on: ubuntu-latest
    needs: exampleJob
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: example-artifact
    - run: cat artifact.txt

