name: manualWorkflow
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: world
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello ${{ github.event.inputs.name }}

