name: subWorkflow
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
jobs:
  simpleJob:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.message }}
